language: node_js

node_js:
  - 4.4.6
before_install:
  - java -version

install:
  - export CXX="g++-4.8"
  - npm install
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils xorriso

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
